title: Hub's application SDK
description: Elements on how to build an application
baseurl: "/sdk" # the subpath of your site, e.g. /blog
url: "https://organizationhub.github.io"
permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

# Enable or disable the site search
search_enabled: true

# Enable or disable heading anchors
#heading_anchors: true

# Color scheme currently only supports "dark" or nil (default)
#color_scheme: dark

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blank_lines: false
  profile: false

remote_theme: pmarsceill/just-the-docs

aux_links:
    "Back to the hub":
      - "//organizationhub.github.io"
